Ads/urls.py
from django.urls import path
from .views import (
    About,
    AdsUpdateView,
    Contact_function,
    DeleteImg,
    FulldataUserView,
    FulldataView,
    HomeItemList,
    AddImagesView,
    AdsCreateView,
    HowTo,
    IjaraAdsCreateView,
    IjaraAdsUpdateView,
    ItemCreateView,
    ItemDeleteView,
    ItemUpdateView,
    OneUserAdsList,
    FilterByCategory,
    EduAdsCreateView,
    EduAdsUpdateView,
    ProductionCreateView,
    ProductionUpdateView,
    SearchList,
)

app_name = 'Ads'

urlpatterns = [
    path('', HomeItemList.as_view(), name='Home'),
    path('about/', About, name='About'),
    path('help/', HowTo, name='Help'),
    path('contact/', Contact_function, name='Contact'),
    path('search/', SearchList.as_view(), name='Search'),
    path('add/', ItemCreateView.as_view(), name='Add'),
    path('one/<pk>/', FulldataView.as_view(), name="Full"),
    path('oneads/<pk>/', FulldataUserView.as_view(), name="FullUser"),
    path('filter/<pk>/', FilterByCategory, name="Filter"),
    path('del/<int:pk>/', DeleteImg.as_view(), name="DelImg"),
    path('delete/<pk>/', ItemDeleteView.as_view(), name='Delete'),
    path('update/<pk>/', ItemUpdateView.as_view(), name='Update'),
    path('addimg/<int:pk>/', AddImagesView.as_view(), name="AddImg"),
    path('personalAds/', OneUserAdsList.as_view(), name='PersonalAds'),
    path('servise/add/', AdsCreateView.as_view(), name='AddWork'),
    path('servise/update/<pk>/', AdsUpdateView.as_view(), name='UpdateWork'),
    path('edu/add/', EduAdsCreateView.as_view(), name='AddEdu'),
    path('edu/update/<pk>/', EduAdsUpdateView.as_view(), name='UpdateEdu'),
    path('production/add/', ProductionCreateView.as_view(), name='AddProduction'),
    path('production/update/<pk>/',
         ProductionUpdateView.as_view(), name='UpdateProduction'),
    path('ijara/add/', IjaraAdsCreateView.as_view(), name='AddIjara'),
    path('ijara/update/<pk>/', IjaraAdsUpdateView.as_view(), name='UpdateIjara'),
]

Ansav_uz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Ads.urls')),
    path('users/', include('Users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.urls import path
from .views import (
    Profile, 
    SignUp_function, 
    LogIn_function,
    Logout_function,
    Update_function,
) 

app_name = 'Users'

urlpatterns = [
    path('', Profile, name='Profile'),
    path('signup/', SignUp_function, name='SignUp'),
    path('login/', LogIn_function, name='LogIn'),
    path('logout/', Logout_function, name='Logout'),
    path('update/', Update_function, name='Update'),
]

Users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='userprofile', on_delete=models.CASCADE)
    image = models.ImageField(default='user.png', upload_to='user_pic')

    def __str__(self):
        return f'{self.user} PROFILE'

    def __unicode__(self):
        return self.user

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        
        if img.width > 300 and img.height > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

Users/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={
        'id': 'email',
        'class': 'form-control',
        'placeholder': 'Emailni kiriting',
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'id': 'password1',
        'class': 'form-control',
        'placeholder': 'passwordni kiriting',
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'id': 'password2',
        'class': 'form-control',
        'placeholder': 'passwordni tasdiqlang',
    }))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={
                'id': 'username',
                'class': 'form-control',
                'placeholder': 'username',
            })
        }

    def save(self, commit=True):
        user = super(NewUserForm, self).save(
            commit=False)  # Call the real save() method
        user.email = self.cleaned_data['email']
        if commit:
           user.save()
        return user


class UpdateUserForm(forms.ModelForm):
    first_name = forms.CharField(required=False, max_length=100)
    last_name = forms.CharField(required=False, max_length=100)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

    def save(self, commit=True):
        user = super(UpdateUserForm, self).save(
            commit=False)  # Call the real save() method
        user.email = self.cleaned_data['email']
        if commit:
           user.save()
        return user


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('image',)

Users/views.py
from .models import UserProfile
from .forms import NewUserForm, UpdateProfileForm, UpdateUserForm
from django.shortcuts import redirect, render
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
# Create your views here.

def Profile(request):
    if request.user.is_authenticated:
        user = request.user
        user, created = UserProfile.objects.get_or_create(user=user)
    return render(request, 'pages/UserHome.html')


def SignUp_function(request):
    if request.user.is_authenticated:
        user = request.user
        user, created = UserProfile.objects.get_or_create(user=user)
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Ro\'yhatdan o\'tish muaffaqiyatli yakunlandi!')
            return redirect('Users:Profile')
        else:
            messages.error(request, f'Kiritilgan malumotlaringizni tekshirib yana bir marta kiriting!')
    form = NewUserForm
    return render(request, 'register/signup.html', context={'form':form})            

def LogIn_function(request):
    if request.user.is_authenticated:
        user = request.user
        user, created = UserProfile.objects.get_or_create(user=user)
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Profilga kirish muaffaqiyatli yakunlandi!')
                return redirect('Users:Profile')
            else:
                messages.error(request, 'username yoki password da xatolik bor tekshirib boshqatdan kiriting!')
        else:
            messages.error(request, 'username yoki password da xatolik bor tekshirib boshqatdan kiriting!')
    form = AuthenticationForm
    return render(request, 'register/login.html', context={'login_form':form})                    

def Logout_function(request):
    logout(request)
    messages.info(request, 'Xayr :( ')
    return redirect('Ads:Home')

def Update_function(request):
    if request.method == 'POST':
        uform = UpdateUserForm(data=request.POST, instance=request.user)
        pform = UpdateProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
        if uform.is_valid() and pform.is_valid():
            uform.save()
            pform.save()
            messages.success(request, 'Profilingiz Muaffaqiyatli Yangilandi!')
            return redirect('Users:Profile')
    else:
        uform = UpdateUserForm(instance=(request.user))
        pform = UpdateProfileForm(request.FILES, instance=(request.user.userprofile))
    context = {
        'uform':uform,
        'pform':pform,
    }
    return render(request, 'pages/update.html', context)

Users/templates/main.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap5.css' %}">
    <!-- fontawesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>
    {% include "pages/messages.html" %}
    <nav class="navbar navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand" href="{% url 'Users:Profile' %}">USER<b class="text-primary">PROFILE</b></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasNavbarLabel">{{user|upper}}</h5>
              <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'Ads:Home' %}"><i class="fas fa-home"></i> Bosh sahifa </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'Ads:PersonalAds' %}"><i class="fas fa-blog"></i> Mening Elonlarim </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'Ads:Add' %}"><i class="fas fa-plus-circle"></i> Elon Qo'shish</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'Ads:AddWork' %}"><i class="fas fa-plus-circle"></i> Ish-xizmatlar qo'shish </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'Ads:AddEdu' %}"><i class="fas fa-plus-circle"></i> Ta'lim yonalishida </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'Ads:AddProduction' %}"><i class="fas fa-plus-circle"></i> Ishlab chiqarish</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'Ads:AddIjara' %}"><i class="fas fa-plus-circle"></i> Ijara uchun elon</a>
                </li>
                <li class="nav-item"> 
                  <a class="nav-link active" aria-current="page" href="{% url 'Users:Update' %}"><i class="fas fa-sliders-h"></i> Sozlamalar</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'Users:Logout' %}"><i class="fas fa-sign-out-alt"></i> SignOut</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </nav>
  <div class="main">
      {% block content %}


      {% endblock content %}
  </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>