Ads/urls.py
from django.urls import path
from .views import (
    About,
    AdsUpdateView,
    Contact_function,
    DeleteImg,
    FulldataUserView,
    FulldataView,
    HomeItemList,
    AddImagesView,
    AdsCreateView,
    HowTo,
    IjaraAdsCreateView,
    IjaraAdsUpdateView,
    ItemCreateView,
    ItemDeleteView,
    ItemUpdateView,
    OneUserAdsList,
    FilterByCategory,
    EduAdsCreateView,
    EduAdsUpdateView,
    ProductionCreateView,
    ProductionUpdateView,
    SearchList,
)

app_name = 'Ads'

urlpatterns = [
    path('', HomeItemList.as_view(), name='Home'),
    path('about/', About, name='About'),
    path('help/', HowTo, name='Help'),
    path('contact/', Contact_function, name='Contact'),
    path('search/', SearchList.as_view(), name='Search'),
    path('add/', ItemCreateView.as_view(), name='Add'),
    path('one/<pk>/', FulldataView.as_view(), name="Full"),
    path('oneads/<pk>/', FulldataUserView.as_view(), name="FullUser"),
    path('filter/<pk>/', FilterByCategory, name="Filter"),
    path('del/<int:pk>/', DeleteImg.as_view(), name="DelImg"),
    path('delete/<pk>/', ItemDeleteView.as_view(), name='Delete'),
    path('update/<pk>/', ItemUpdateView.as_view(), name='Update'),
    path('addimg/<int:pk>/', AddImagesView.as_view(), name="AddImg"),
    path('personalAds/', OneUserAdsList.as_view(), name='PersonalAds'),
    path('servise/add/', AdsCreateView.as_view(), name='AddWork'),
    path('servise/update/<pk>/', AdsUpdateView.as_view(), name='UpdateWork'),
    path('edu/add/', EduAdsCreateView.as_view(), name='AddEdu'),
    path('edu/update/<pk>/', EduAdsUpdateView.as_view(), name='UpdateEdu'),
    path('production/add/', ProductionCreateView.as_view(), name='AddProduction'),
    path('production/update/<pk>/',
         ProductionUpdateView.as_view(), name='UpdateProduction'),
    path('ijara/add/', IjaraAdsCreateView.as_view(), name='AddIjara'),
    path('ijara/update/<pk>/', IjaraAdsUpdateView.as_view(), name='UpdateIjara'),
]

Ansav_uz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Ads.urls')),
    path('users/', include('Users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.urls import path
from .views import (
    Profile, 
    SignUp_function, 
    LogIn_function,
    Logout_function,
    Update_function,
) 

app_name = 'Users'

urlpatterns = [
    path('', Profile, name='Profile'),
    path('signup/', SignUp_function, name='SignUp'),
    path('login/', LogIn_function, name='LogIn'),
    path('logout/', Logout_function, name='Logout'),
    path('update/', Update_function, name='Update'),
]

Ads/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

length = 150


class Category(models.Model):
    name = models.CharField(max_length=length, blank=True, null=True)
    add_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class ItemName(models.Model):
    creater = models.ForeignKey(
        User, related_name='creater', on_delete=models.CASCADE)
    name = models.CharField(max_length=length, blank=True, null=True)
    ijara_turi = models.CharField(max_length=length, blank=True, null=True)
    narx = models.CharField(max_length=length, blank=True, null=True)
    category = models.ForeignKey(
        Category, related_name='category', on_delete=models.CASCADE)
    campany_name = models.CharField(max_length=length, blank=True, null=True)
    work_type = models.CharField(max_length=length, blank=True, null=True)
    image = models.ImageField(default='ish.jpg', upload_to='item_img')
    teaching_subject = models.CharField(
        max_length=length, blank=True, null=True)
    center_or_teacher_name = models.CharField(
        max_length=length, blank=True, null=True)
    region = models.CharField(max_length=length, blank=True, null=True)
    contact_person = models.CharField(max_length=length, blank=True, null=True)
    contact_number = models.CharField(max_length=length, blank=True, null=True)
    contact_person1 = models.CharField(
        max_length=length, blank=True, null=True)
    contact_number1 = models.CharField(
        max_length=length, blank=True, null=True)
    about = models.TextField()
    add_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('Ads:Home', kwargs={'pk': self.pk})

    @property
    def allimages(self):
        allImg = self.images_set.all
        return allImg

    def __str__(self):
        return f'{self.name} by {self.creater}'

    def __unicode__(self):
        return self.name


class Images(models.Model):
    itemname = models.ForeignKey(
        ItemName, on_delete=models.CASCADE, blank=True, null=True)
    images = models.ImageField(upload_to='item_img')

    def __str__(self):
        return f'Image of {self.itemname}'

    def __unicode__(self):
        return self.itemname

Ads/forms.py
from django import forms
from .models import ItemName

class NewItemForm(forms.ModelForm):
    contact_person1 = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'id':'person1',
        'class':'form-control',
        'placeholder':'Example*** Azam',        
    }))
    contact_number1 = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':'Example*** 33 233 13 23',        
    }))
    teaching_subject = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':'Example*** Rus tili',                
    }))
    center_or_teacher_name = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':'Example*** Learning Center',                
    }))
    about = forms.CharField(required=False, widget=forms.Textarea(attrs={
        'id':'area',
        'style':'height: 130px;',
        'class':'form-control',
        'placeholder':'Example*** Xaqida',
    }))
    name = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'id':'name',
        'class':'form-control',
        'placeholder':'Example*** exampleThing',
    }))
    work_type = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'id':'type',
        'class':'form-control',
        'placeholder':'Example*** Benzapila Xizmati',
    }))
    campany_name = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'id':'cam_name',
        'class':'form-control',
        'placeholder':'Example*** "exampleCampany"',
    }))
    ijara_turi = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'id':'iname',
        'class':'form-control',
        'placeholder':'Example*** Avtomobile',
    }))
    class Meta:
        model = ItemName
        fields = ['name', 'ijara_turi','campany_name','category', 'work_type', 'narx', 'image', 'region', 'contact_person', 'contact_number','contact_person1', 'contact_number1', 'about', 'teaching_subject', 'center_or_teacher_name', ]
        widgets = {
            'narx':forms.TextInput(attrs={
                'id':'narx',
                'class':'form-control',
                'placeholder':'Example*** 800 000',
            }),
            'image':forms.FileInput(attrs={
                'id':'img',
                'class':'form-control',
            }),
            'category':forms.Select(attrs={
                'id':'group',
                'class':'form-select',
            }),
            'region':forms.TextInput(attrs={
                'id':'region',
                'class':'form-control',
                'placeholder':'Example*** Andijon',
            }),
            'contact_person':forms.TextInput(attrs={
                'id':'person',
                'class':'form-control',
                'placeholder':'Example*** Murod',
            }),
            'contact_number':forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'Example*** 91 626 16 76',
            }),
        }

class ContactForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'id':'fname',
        'placeholder':'name',
        'class':'form-control',
    }) , max_length=150)
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'id':'lname',
        'class':'form-control',
        'placeholder':'name2',
    }) , max_length=150)
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'id':'email',
        'class':'form-control',
        'placeholder':'email',
    }) , max_length=150)
    message = forms.CharField(widget=forms.Textarea(attrs={
        'id':'area',
        'class':'form-control',
        'placeholder':'messages',
        'style':'height:150px;'
    }), max_length=2000)

Ads/views.py
from .forms import ContactForm, NewItemForm
from django.shortcuts import redirect, render
from django.http.response import HttpResponse
from .models import Category, Images, ItemName
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.core.mail import send_mail, BadHeaderError
from django.conf import settings
from django.db.models import Q
# Create your views here:


def About(request):
    return render(request, 'Adspages/about.html')


def HowTo(request):
    return render(request, 'Adspages/help.html')


class HomeItemList(ListView):
    model = ItemName
    template_name = 'Adspages/Home.html'
    ordering = '-add_date'
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context


def FilterByCategory(request, pk):
    ads = ItemName.objects.filter(category=pk)
    category = Category.objects.all()
    context = {
        'pk': pk,
        'ads': ads,
        'category': category,
    }
    return render(request, 'Adspages/filter_by_category.html', context)


class FulldataView(TemplateView):
    template_name = 'Adspages/full_data.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['obj'] = ItemName.objects.get(pk=self.kwargs['pk'])
        return context


class AddImagesView(TemplateView):
    template_name = 'Adspages/add_images.html'

    def post(self, *args, **kwargs):
        try:
            images = self.request.FILES.getlist('images')
            itemname = ItemName.objects.get(pk=self.kwargs['pk'])
            for i in images:
                itemname_images = Images.objects.create(
                    itemname=itemname, images=i)
            return redirect('Ads:Home')
        except Exception as e:
            print(e)
            return HttpResponse('Ishlamadi')


class DeleteImg(DeleteView):
    model = Images
    success_url = '/personalAds/'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class ItemCreateView(CreateView):
    model = ItemName
    form_class = NewItemForm
    template_name = 'Adspages/add.html'
    success_url = '/personalAds/'

    def form_valid(self, form):
        form.instance.creater = self.request.user
        return super().form_valid(form)


class ItemUpdateView(UpdateView):
    model = ItemName
    form_class = NewItemForm
    template_name = 'Adspages/update_item.html'
    success_url = '/personalAds/'

    def form_valid(self, form):
        form.instance.creater = self.request.user
        return super().form_valid(form)

    def test_func(self):
        ads = self.get_object()
        if self.request.user == ads.creater:
            return True
        return False


class ItemDeleteView(DeleteView):
    model = ItemName
    success_url = '/personalAds/'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def test_func(self):
        ads = self.get_object()
        if self.request.user == ads.creater:
            return True
        return False


class OneUserAdsList(ListView):
    model = ItemName
    template_name = 'Adspages/oneUserAds.html'
    ordering = '-add_date'

    def get_queryset(self):
        return ItemName.objects.filter(creater=self.request.user).reverse()

#Ish-xizmatlari eloni qoshish:


class AdsCreateView(CreateView):
    model = ItemName
    form_class = NewItemForm
    template_name = 'otherPages/add_servises.html'
    success_url = '/personalAds/'

    def form_valid(self, form):
        form.instance.creater = self.request.user
        return super().form_valid(form)


class AdsUpdateView(UpdateView):
    model = ItemName
    form_class = NewItemForm
    template_name = 'otherPages/update_servises.html'
    success_url = '/personalAds/'

    def form_valid(self, form):
        form.instance.creater = self.request.user
        return super().form_valid(form)

    def test_func(self):
        ads = self.get_object()
        if self.request.user == ads.creater:
            return True
        return False

# add ijara ads


class IjaraAdsCreateView(CreateView):
    model = ItemName
    form_class = NewItemForm
    template_name = 'otherPages/add_ijara.html'
    success_url = '/personalAds/'

    def form_valid(self, form):
        form.instance.creater = self.request.user
        return super().form_valid(form)


class IjaraAdsUpdateView(UpdateView):
    model = ItemName
    form_class = NewItemForm
    template_name = 'otherPages/update_ijara.html'
    success_url = '/personalAds/'

    def form_valid(self, form):
        form.instance.creater = self.request.user
        return super().form_valid(form)

    def test_func(self):
        ads = self.get_object()
        if self.request.user == ads.creater:
            return True
        return False

# Adding education Ads


class EduAdsCreateView(CreateView):
    model = ItemName
    form_class = NewItemForm
    template_name = 'otherPages/add_education.html'
    success_url = '/personalAds/'

    def form_valid(self, form):
        form.instance.creater = self.request.user
        return super().form_valid(form)


class EduAdsUpdateView(UpdateView):
    model = ItemName
    form_class = NewItemForm
    template_name = 'otherPages/update_edu.html'
    success_url = '/personalAds/'

    def form_valid(self, form):
        form.instance.creater = self.request.user
        return super().form_valid(form)

    def test_func(self):
        ads = self.get_object()
        if self.request.user == ads.creater:
            return True
        return False

# Adding IShlab chiqarish!


class ProductionCreateView(CreateView):
    model = ItemName
    form_class = NewItemForm
    template_name = 'otherPages/add_production.html'
    success_url = '/personalAds/'

    def form_valid(self, form):
        form.instance.creater = self.request.user
        return super().form_valid(form)


class ProductionUpdateView(UpdateView):
    model = ItemName
    form_class = NewItemForm
    template_name = 'otherPages/update_production.html'
    success_url = '/personalAds/'

    def form_valid(self, form):
        form.instance.creater = self.request.user
        return super().form_valid(form)

    def test_func(self):
        ads = self.get_object()
        if self.request.user == ads.creater:
            return True
        return False


# add contact section

def Contact_function(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = 'Contact Subject'
            body = {
                'first_name': form.cleaned_data['first_name'],
                'last_name': form.cleaned_data['last_name'],
                'email': form.cleaned_data['email'],
                'message': form.cleaned_data['message'],
            }
            message = "\n".join(body.values())

            try:
                send_mail(subject, message, body['email'], [
                          settings.EMAIL_HOST_USER])
            except BadHeaderError:
                return HttpResponse('Hato')
            return redirect('Ads:Contact')

    form = ContactForm
    return render(request, 'Adspages/contact.html', {"form": form})

# add search section


class SearchList(ListView):
    model = ItemName
    template_name = 'Adspages/search.html'
    ordering = '-add_date'
    paginate_by = 8

    def get_queryset(self):
        query = self.request.GET.get('search')
        object_list = ItemName.objects.filter(
            Q(name__icontains=query) | Q(region__icontains=query) | Q(
                campany_name__icontains=query) | Q(work_type__icontains=query)
            | Q(teaching_subject__icontains=query) | Q(
                center_or_teacher_name__icontains=query)
            | Q(narx__icontains=query) | Q(ijara_turi__icontains=query)
        )
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context


class FulldataUserView(TemplateView):
    template_name = 'Adspages/full_Data_user.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['obj'] = ItemName.objects.get(pk=self.kwargs['pk'])
        return context

Ads/templates/Adspages/add_images.html
{% extends "index.html" %}
{% load static %}
{% block title %}
    AddImages
{% endblock title %}
{% block content %}

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" multiple name="images" class="form-control">
        <br>    
        <br>
        <input type="submit" value="Add" class="btn btn-outline-primary">
    </form>

{% endblock content %}

Ads/templates/Adspages/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- fontawesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body class="bg-white">
    {% include "pages/messages.html" %}
    <style>
        #fon-img{
            color: white;   
            text-shadow: red;
            font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
            width: 100%;
            height: 80vh;
            background-image: url("{% static 'images/laptopt.jpg' %}");
            background-position: center;
            background-clip: border-box;
            background-repeat: no-repeat;
            background-size: cover;
        }
        @media (min-width: 320px) and (max-width: 481px) {
            #fon-img{
                width: 100%;
                height: 80vh;
                background-image: url("{% static 'images/mobile2.jpg' %}");
                background-position: center;
                background-repeat: no-repeat;
                background-size: cover;
            }
        }
        @media (min-width: 481px) and (max-width: 767px) {
            #fon-img{
                width: 100%;
                height: 80vh;
                background-image: url("{% static 'images/ipad2.jpg' %}");
                background-position: center;
                background-repeat: no-repeat;
                background-size: cover;
            }
        }
        @media (min-width: 1024px) {
            #fon-img{
                width: 100%;
                height: 80vh;
                background-image: url("{% static 'images/laptopt.jpg' %}");
                background-position: center;
                background-clip: border-box;
                background-repeat: no-repeat;
                background-size: cover;
            }
        }
        #title{
            left: 7%;
            top: 17%;
            position: relative;
        }
    </style>
    <div class="row" style="margin-right: 0;">
        <div class="col-12 col-sm-12 col-md-10 col-lg-10 col-xl-10 m-auto">
            <div class="container-fluid">    
                <nav class="navbar navbar-expand-lg navbar-light bg-light rounded" aria-label="Eleventh navbar example">
                    <div class="container-fluid">
                    <a class="navbar-brand" href="/">Ansav.Uz</a>
                    <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
            
                    <div class="navbar-collapse collapse" id="navbarsExample09">
                        <form class="d-flex mt-3 mt-lg-0 me-0 me-sm-0 me-md-auto me-lg-auto w-100" method="get" action="{% url 'Ads:Search' %}">
                            <input name="search" class="form-control me-auto rounded-pill form-control-sm" type="search" placeholder="Search" aria-label="Search">
                        </form>
                        <div class="text-center text-sm-center text-md-center ms-auto ms-lg-5 mt-lg-0 mt-2 d-inline-block">
                            {% if user.is_authenticated %}
                                <a href="{% url 'Users:Profile' %}">
                                    <img src="{{user.userprofile.image.url}}" width="35" alt="userimg">
                                </a>
                            {% else %}  
                                <div class="btn-group text-center text-sm-center text-md-center">
                                    <a href="{% url 'Users:LogIn' %}" class="btn btn-outline-success btn-sm">LogIn</a>
                                    <a href="{% url 'Users:SignUp' %}" class="btn btn-outline-warning btn-sm">SignUp</a>
                                </div>  
                            {% endif %}
                        </div>
                    </div>
                    </div>
                </nav> <!--navbar-->
                
                <nav class="navbar navbar-expand-lg navbar-light bg-light rounded" aria-label="Twelfth navbar example">
                    <div class="container-fluid">
                    <div class="m-auto">
                        <ul class="nav" id="nav_ul">
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="/">Bosh sahifa</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'Ads:About' %}">Biz Haqimizda</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'Ads:Contact' %}">Contact</a>
                            </li>
                        </ul>
                    </div><br>
                </div>
            </nav> 
            <nav class="navbar navbar-expand-lg navbar-light bg-light rounded" aria-label="Twelfth navbar example">
                <div class="m-auto">
                    <ul class="nav text-center">
                        <li class="nav-item">
                            <a href="/" class="nav-link">All</a>
                        </li>
                        {% for i in category %}                              
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'Ads:Filter' pk=i.pk %}">{{i.name}}</a>
                            </li>
                        {% endfor %} 
                    </ul>
                </div>
            </nav>
    
                <div id="fon-img">
                  <div class="p-5 rounded" id="title">
                    <div class="col-sm-8 mx-auto">
                      <h1>Ansav.Uz Online <br> Internet Bozor</h1>
                      <p>Biz bilan yanada tezroq!</p>
                      <p>
                        {% if user.is_authenticated %}
                          
                        {% else %}       
                          <p>Hoziroq royhatdan o'ting va soting!</p>
                            <a class="btn btn-primary btn-sm" href="{% url 'Users:SignUp' %}" role="button">Ro'yhatdan O'tish »</a>
                        {% endif %}
                      </p>
                    </div>
                  </div>
                </di>
                </div>
              
                <div class="wrapper text-center py-4 bg-light">
                    <h4 class="m-0">Eng Yangi E'lonlar</h4>
                </div>    
  <div class="main">
      {% block content %}


      {% endblock content %}
  </div>
  
  <footer>
    <div class="bg-light py-3 footer-bottom">
        <div class="row px-4">
            <div class="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
                <ul class="list-unstyled">
                    {% for i in category %}
                        <li><a class="" href="{% url 'Ads:Filter' pk=i.pk %}">{{i.name}}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
                <ul class="list-unstyled">
                    <li><a href="/">Bosh sahifa</a></li>
                    <li><a href="{% url 'Ads:About' %}">Biz Haqimizda</a></li>
                    <li><a href="{% url 'Ads:Contact' %}">Contact</a></li>
                    <li><a href="{% url 'Ads:Help' %}">Qanday qilib elon Beraman ?</a></li>
                </ul>
            </div>
            <div class="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
                <div class="telegram">
                    <span>Bizni Telegamda Kuzting!</span>
                    <samp><a href="http://t.me@an_sav1">http://t.me@an_sav1</a></samp>
                </div>
                <div class="ilova d-grid gap-2 mt-3">
                    <span>Mobil Ilovamizni ham yuklab oling!</span>
                    <a href="#" class="btn btn-sm btn-outline-success">Yuklab Olish</a>
                </div>
            </div>
        </div>
        <div class="text-center">
            <span class="">Ansav.Uz &copy; 2021</span>
        </div>
    </div>
</footer>
</div>
</div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

Ads/templates/Adspages/delete_item.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>
        {{object.name}}
    </p>
    <input type="submit" value="submit">
</form>

Ads/templates/Adspages/oneUserAds.html
{% extends "main.html" %}
{% load static %}
{% load bootstrap5 %}
{% block title %}
    PersonalAds
{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        {% for i in object_list %}  
            <div class="col-6 col-sm-6 col-md-4 col-lg-4 col-xl-3 my-3 box-element">
                <div class="card">
                    <img src="{{i.image.url}}" alt="" height="200" class="card-img-top">
                    <div class="card-body">
                        {% if i.center_or_teacher_name or i.teaching_subject %}
                            <span id="markaz" class="border-bottom border-primary">{{i.category}}</span><br>
                            <span class="card-title">{{i.teaching_subject}}</span>
                        {% elif i.work_type %}
                            <span id="markaz" class="border-bottom border-primary">{{i.category}}</span><br>
                            <span class="card-title">{{i.work_type}}</span>
                        {% else %}
                            <span id="markaz" class="border-bottom border-primary">{{i.category}}</span><br>
                            <span class="card-title">{{i.name}}</span>
                        {% endif %}
                        <p class="card-text mb-2">Narxi: {{i.narx}} so'm</p>
                        <span class="text-secondary"> <small> E'lon qilingan kun: {{ i.add_date }}</small> </span><br>
                        <div class="d-grid gap-2 mt-1">
                            <a href="{% url 'Ads:FullUser' pk=i.pk %}" class="btn btn-sm btn-secondary rounded-0">Nazar solish</a>
                        </div>
                        <div class="mt-3 d-grid gap-2" role="group">
                            {% if i.center_or_teacher_name and not i.work_type %}
                                <a href="{% url 'Ads:UpdateEdu' pk=i.pk %}" class="btn btn-outline-info px-3 btn-sm">Edit</a>
                            {% elif i.work_type %}
                                <a href="{% url 'Ads:UpdateWork' pk=i.pk %}" class="btn btn-outline-info px-3 btn-sm">Edit</a>
                            {% elif i.campany_name %}
                                <a href="{% url 'Ads:UpdateProduction' pk=i.pk %}" class="btn btn-outline-info px-3 btn-sm">Edit</a>
                            {% elif i.ijara_turi %}
                                <a href="{% url 'Ads:UpdateIjara' pk=i.pk %}" class="btn btn-outline-info px-3 btn-sm">Edit</a>
                            {% else %}
                                <a href="{% url 'Ads:Update' pk=i.pk %}" class="btn btn-outline-info px-3 btn-sm">Edit</a>
                            {% endif %}
                            <form action="{% url 'Ads:Delete' pk=i.pk %}" method="post" class="d-grid gap-2">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                            </form>
                            <!-- <a href="{% url 'Ads:AddImg' pk=i.pk %}" class="btn btn-outline-success">Add</a> -->
                        </div>
                    </div>
                </div>  
            </div>
        {% endfor %}
    </div> <!-- cartitems -->
</div>


{% endblock content %}